# Configuration for terraform-docs diagram
diagrams:
  enabled: true
  title: "AWS VPC Infrastructure"
  provider: "aws"
  output:
    file: "docs/vpc-diagram.png"
    format: png
  show:
    - aws_vpc
    - aws_subnet
    - aws_internet_gateway
    - aws_nat_gateway
    - aws_route_table
    - aws_route_table_association
    - aws_eip
